var css = [
  '.dshw_anchor{display:inline-flex;align-items:center;min-height:22px;min-width:0;vertical-align:middle}',
  '.dshw_anchorHome{overflow:hidden;min-width:44px}',
  '.dshw_chipLift{z-index:80!important}',
  '.dshw_anchorHome>.dshw_chip{box-sizing:border-box;max-width:100%;min-width:0;overflow:hidden}',
  '.dshw_chip{border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));background:transparent;height:22px;color:var(--dsw-alias-label-primary,inherit);white-space:nowrap;border-radius:999px;align-items:stretch;font-size:12px;line-height:1;display:inline-flex;position:relative;touch-action:none;user-select:none;cursor:grab}',
  '.dshw_chip:hover,.dshw_chip:focus-within{border-color:var(--dsw-alias-brand-primary,#4aa3ff)}',
  '.dshw_chipLow{border-color:var(--dsw-alias-state-error-primary,#e5534b);color:var(--dsw-alias-state-error-primary,#e5534b);animation:dshwChipPulseIn 1.8s ease-in-out infinite}',
  '.dshw_chipLow:hover,.dshw_chipLow:focus-within{border-color:var(--dsw-alias-state-error-primary,#e5534b)}',
  '.dshw_chipDocked{position:fixed;z-index:79;background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,#1e1e20));box-shadow:0 2px 10px rgba(0,0,0,.25)}',
  '.dshw_chipDragging{cursor:grabbing;box-shadow:0 6px 18px rgba(0,0,0,.3)}',
  '.dshw_snapPreview{position:fixed;z-index:78;pointer-events:none;box-sizing:border-box;border:2px dashed var(--dsw-alias-brand-primary,#4aa3ff);background:rgba(74,163,255,.10);box-shadow:0 0 0 3px rgba(74,163,255,.10);border-radius:999px;transition:left .06s ease,top .06s ease,width .06s ease,height .06s ease}',
  '.dshw_snapPreviewVertical{border-radius:7px}',
  '.dshw_chipVertical{height:auto;width:40px;min-width:40px;max-width:40px;box-sizing:border-box;overflow:hidden;flex-direction:column;border-radius:7px;align-items:stretch;white-space:normal;font-size:10px;line-height:1.1}',
  '.dshw_chipVertical .dshw_chipMain{width:100%;box-sizing:border-box;flex-direction:column;align-items:stretch;gap:0;padding:0;border-radius:7px 7px 0 0}',
  '.dshw_chipVertical .dshw_chipMain>span{display:flex;flex-direction:column;align-items:center;gap:1px;padding:2px 0;text-align:center}',
  '.dshw_chipVertical .dshw_metricLabel{opacity:.72}',
  '.dshw_chipVertical .dshw_metricValue{font-variant-numeric:tabular-nums}',
  '.dshw_chipVertical .dshw_sep{display:none}',
  '.dshw_chipVertical .dshw_recharge{width:100%;box-sizing:border-box;border-left:0;border-top:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));padding:3px 1px;justify-content:center;border-radius:0 0 7px 7px}',
  '.dshw_bottomDockHost{box-sizing:border-box!important;padding-bottom:30px!important}',
  '@keyframes dshwChipPulseIn{0%,100%{box-shadow:inset 0 0 0 0 rgba(229,83,75,0)}50%{box-shadow:inset 0 0 0 3px rgba(229,83,75,.32)}}',
  '@keyframes dshwPulse{0%,100%{box-shadow:0 0 0 0 rgba(229,83,75,.45)}50%{box-shadow:0 0 0 5px rgba(229,83,75,0)}}',
  '.dshw_sep{opacity:.45}',
  '.dshw_chipMain,.dshw_recharge{border:0;background:transparent;color:inherit;font:inherit;cursor:pointer;align-items:center;display:inline-flex;gap:6px;margin:0}',
  '.dshw_chipMain{padding:0 7px;border-radius:999px 0 0 999px}',
  '.dshw_chipNoRecharge .dshw_chipMain{border-radius:999px}',
  '.dshw_chipVertical.dshw_chipNoRecharge .dshw_chipMain{border-radius:7px}',
  '.dshw_recharge{color:var(--dsw-alias-brand-primary,#4aa3ff);border-left:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));padding:0 7px 0 6px;border-radius:0 999px 999px 0}',
  '.dshw_chipBalanceOnly .dshw_chipMain{border-radius:999px}',
  'body[data-dsh-maid-atelier] .dshw_anchorHome{min-height:38px;border-radius:999px}',
  'body[data-dsh-maid-atelier] .dshw_anchorHome>.dshw_chip{height:38px;border-color:var(--dsw-alias-border-l2,rgba(211,180,119,.66));background:var(--dsw-alias-button-elevated-fill,rgba(28,44,84,.72));background-clip:padding-box;box-shadow:inset 0 0 0 3px rgba(255,255,255,.04);backdrop-filter:none;isolation:isolate}',
  'body[data-dsh-maid-atelier] [data-composer-card] button.dshw_chipMain[aria-haspopup="dialog"]{box-sizing:border-box;width:auto;min-width:0;max-width:none;height:100%;padding:0 9px;border:0;border-radius:999px 0 0 999px;color:inherit;background:transparent;box-shadow:none;transform:none}',
  'body[data-dsh-maid-atelier] [data-composer-card] button.dshw_chipMain[aria-haspopup="dialog"]:hover:not(:disabled){transform:none;background:var(--dsw-alias-interactive-bg-hover,rgba(255,252,243,.1))}',
  'body[data-dsh-maid-atelier] [data-composer-card] .dshw_chipNoRecharge button.dshw_chipMain[aria-haspopup="dialog"]{border-radius:999px}',
  'body[data-dsh-maid-atelier] [data-composer-card] button.dshw_recharge{height:100%;border:0;border-left:1px solid var(--dsw-alias-border-l2,rgba(211,180,119,.66));background:transparent;box-shadow:none;transform:none}',
  'body[data-dsh-maid-atelier] [data-composer-card] button.dshw_recharge:hover:not(:disabled){transform:none;background:var(--dsw-alias-interactive-bg-hover,rgba(255,252,243,.1))}',
  'body[data-dsh-maid-atelier] [data-composer-card].dshw_modelMenuOpen{backdrop-filter:none!important;-webkit-backdrop-filter:none!important}',
  'body[data-dsh-maid-atelier] [data-composer-card].dshw_modelMenuOpen [role="menu"]{background:rgba(232,238,249,.98)!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}',
  'body[data-dsh-maid-atelier][data-ds-dark-theme] [data-composer-card].dshw_modelMenuOpen [role="menu"]{background:rgba(24,40,80,.98)!important}',
  '.dshw_chipMain:focus-visible,.dshw_recharge:focus-visible,.dshw_btn:focus-visible,.dshw_floatBtn:focus-visible,.dshw_dot:focus-visible{outline:2px solid var(--dsw-alias-brand-primary,#4aa3ff);outline-offset:2px}',
  '.dshw_panel{z-index:40;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,transparent)));box-sizing:border-box;width:min(276px,calc(100vw - 12px));max-height:calc(100vh - 16px);overflow:auto;color:var(--dsw-alias-label-primary,inherit);border-radius:8px;flex-direction:column;gap:4px;padding:8px 9px;font-size:12px;display:flex;position:fixed;box-shadow:0 4px 16px rgba(0,0,0,.35)}',
  '.dshw_panelHeader{min-height:30px;cursor:move;touch-action:none;user-select:none;border-bottom:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.2));padding-bottom:5px}',
  '.dshw_panelHeader .dshw_btn{cursor:pointer}',
  '.dshw_panelDragLabel{display:inline-flex;align-items:center;gap:5px;font-weight:600;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '.dshw_providerTabs{display:grid;grid-template-columns:1fr 1fr;gap:4px;padding:3px;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.22));border-radius:7px;background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,rgba(127,127,127,.06)))}',
  '.dshw_providerTab{min-height:28px;border:0;border-radius:5px;background:transparent;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085));font:inherit;font-weight:600;cursor:pointer}',
  '.dshw_providerTab[aria-pressed="true"]{background:var(--dsw-alias-brand-primary,#4aa3ff);color:var(--dsw-alias-label-primary-foreground,var(--dsw-alias-label-primary,inherit));box-shadow:0 1px 3px rgba(0,0,0,.16)}',
  '.dshw_providerTab:focus-visible{outline:2px solid var(--dsw-alias-brand-primary,#4aa3ff);outline-offset:2px}',
  '.dshw_row{justify-content:space-between;align-items:center;gap:6px;display:flex}',
  '.dshw_row>span:last-child{text-align:right;overflow-wrap:anywhere}',
  '.dshw_title{font-weight:600;opacity:.9}',
  '.dshw_muted{color:var(--dsw-alias-label-tertiary,var(--dsw-alias-label-secondary,#667085))}',
  '.dshw_divider{border-top:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.2));margin-top:1px;padding-top:4px}',
  '.dshw_input{background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,rgba(127,127,127,.08)));border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));color:var(--dsw-alias-label-primary,inherit);border-radius:5px;padding:3px 6px;width:56px;font-size:12px}',
  '.dshw_scaleControl{display:flex;align-items:center;gap:7px;min-width:126px;justify-content:flex-end}',
  '.dshw_scaleInput{width:78px;accent-color:var(--dsw-alias-brand-primary,#4aa3ff);cursor:pointer}',
  '.dshw_scaleValue{width:34px;text-align:right;font-variant-numeric:tabular-nums}',
  '.dshw_visibilityControl{display:flex;align-items:center;gap:7px}',
  '.dshw_check{display:inline-flex;align-items:center;gap:4px;cursor:pointer;white-space:nowrap}',
  '.dshw_check input{margin:0;accent-color:var(--dsw-alias-brand-primary,#4aa3ff)}',
  '.dshw_select{background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,rgba(127,127,127,.08)));border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));color:var(--dsw-alias-label-primary,inherit);border-radius:5px;padding:2px 4px;font-size:12px}',
  '.dshw_btn{border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));background:var(--dsw-alias-bg-layer-1,transparent);color:var(--dsw-alias-label-primary,inherit);border-radius:5px;padding:2px 6px;font-size:12px;cursor:pointer}',
  '.dshw_btnPrimary{background:var(--dsw-alias-brand-primary,#4aa3ff);border-color:transparent;color:var(--dsw-alias-label-primary-foreground,var(--dsw-alias-label-primary,inherit))}',
  '.dshw_historyCard{position:relative;margin:4px 0;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.2));border-radius:8px;background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,rgba(127,127,127,.04)));overflow:hidden;color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_historyHeader{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px 9px}',
  '.dshw_historyTitleCopy{display:flex;min-width:0;flex-direction:column;gap:2px}',
  '.dshw_historyTitleCopy strong{font-size:12px;font-weight:650}',
  '.dshw_historyTitleCopy span{font-size:10px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '.dshw_historySummary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px;padding:0 9px 8px}',
  '.dshw_historySummary>div{min-width:0;display:flex;flex-direction:column;gap:2px}',
  '.dshw_historySummary span{font-size:9.5px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '.dshw_historySummary strong{font-size:11px;font-variant-numeric:tabular-nums;white-space:nowrap}',
  '.dshw_historyMetricToggle{display:flex;justify-content:flex-end;gap:3px;padding:0 9px 5px}',
  '.dshw_historyMetricToggle button{border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.16));background:transparent;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085));border-radius:4px;padding:2px 6px;font-size:9.5px;cursor:pointer}',
  '.dshw_historyMetricToggle button:hover,.dshw_historyMetricActive{border-color:var(--dsw-alias-brand-primary,#4aa3ff)!important;color:var(--dsw-alias-label-primary,inherit)!important;background:var(--dsw-alias-interactive-bg-hover,rgba(127,127,127,.08))!important}',
  '.dshw_historyLegend{display:flex;align-items:center;justify-content:flex-end;gap:3px;padding:0 9px 5px;font-size:9px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '.dshw_historySwatch{width:10px;height:10px;border-radius:2px;border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.12))}',
  '.dshw_historyChart{position:relative;min-height:100px}',
  '.dshw_historyWeekLabels{position:absolute;left:5px;top:4px;display:grid;grid-template-rows:repeat(7,12px);gap:2px;font-size:8px;line-height:12px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '.dshw_historyHeatmap{display:grid;grid-template-rows:repeat(7,12px);grid-auto-flow:column;grid-auto-columns:12px;gap:2px;overflow-x:auto;min-height:96px;margin:0 8px 8px;padding:2px 4px 2px 19px}',
  '.dshw_historyCell{box-sizing:border-box;width:12px;height:12px;padding:0;border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.12));border-radius:2px;background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,rgba(127,127,127,.08)));cursor:pointer}',
  '.dshw_historyCell:hover,.dshw_historyCell:focus-visible{outline:1px solid var(--dsw-alias-brand-primary,#4aa3ff);outline-offset:1px}',
  '.dshw_historyCellToday{box-shadow:inset 0 0 0 1px var(--dsw-alias-label-primary,currentColor)}',
  '.dshw_historyCellSelected{outline:2px solid var(--dsw-alias-brand-primary,#4aa3ff);outline-offset:1px}',
  '.dshw_historyCell1{background:var(--dsw-alias-state-success-soft,rgba(26,127,55,.18))}',
  '.dshw_historyCell2{background:var(--dsw-alias-state-success-muted,rgba(26,127,55,.36))}',
  '.dshw_historyCell3{background:var(--dsw-alias-state-success-muted,rgba(26,127,55,.62))}',
  '.dshw_historyCell4{background:var(--dsw-alias-state-success-primary,#1a7f37)}',
  '.dshw_historyDetail{border-top:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.12));padding:7px 9px}',
  '.dshw_historyDetailHeader,.dshw_historyDetailRow,.dshw_historyActions{display:flex;align-items:center;justify-content:space-between;gap:7px}',
  '.dshw_historyDetailHeader{margin-bottom:4px;font-size:10.5px}',
  '.dshw_historyDetailRow{min-width:0;padding:3px 0;font-size:10px}',
  '.dshw_historyDetailName{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.dshw_historyActions{padding:6px 9px;border-top:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.12));font-size:9.5px;flex-wrap:wrap}',
  '.dshw_historyActions .dshw_muted{min-width:150px;flex:1 1 100%;line-height:1.35}',
  '.dshw_historyEmpty{padding:10px 9px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085));font-size:10.5px}',
  // ---- v0.2 panel restyle: balance card, settings card, account scroll ----
  '.dshw_balanceCard{margin:2px 0 2px;padding:8px 10px;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.2));border-radius:8px;background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,rgba(127,127,127,.06)))}',
  '.dshw_balLine{display:flex;align-items:center;gap:7px;white-space:nowrap}',
  '.dshw_balNum{font-size:18px;font-weight:650;line-height:1.1;letter-spacing:-.01em;font-variant-numeric:tabular-nums}',
  '.dshw_balWarn{display:inline-flex;align-items:center;gap:4px;padding:1px 6px;border-radius:999px;background:var(--dsw-alias-state-error-soft,rgba(229,83,75,.12));color:var(--dsw-alias-state-error-primary,#e5534b);font-size:10px;font-weight:500;line-height:16px;white-space:nowrap}',
  '.dshw_balWarn::before{content:"";width:5px;height:5px;border-radius:50%;background:var(--dsw-alias-state-error-primary,#e5534b);animation:dshwPulse 1.8s infinite}',
  '.dshw_balFill{flex:1}',
  '.dshw_balSession{text-align:right;white-space:nowrap}',
  '.dshw_balSession .dshw_muted{margin-right:5px}',
  '.dshw_balSessionNum{font-size:13px;font-weight:600;font-variant-numeric:tabular-nums}',
  '.dshw_balSub{margin-top:4px;font-size:11px;color:var(--dsw-alias-label-secondary,rgba(127,127,127,.85));display:flex;align-items:center;gap:7px;white-space:nowrap}',
  '.dshw_balSub .dshw_balDot{color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '.dshw_setCard{border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.2));border-radius:8px;background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,transparent));overflow:hidden;margin:2px 0}',
  '.dshw_setCell{display:flex;align-items:center;gap:8px;padding:6px 9px;min-height:34px;color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_setCell+.dshw_setCell{border-top:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.12))}',
  '.dshw_setCell:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(127,127,127,.08))}',
  '.dshw_setCell .dshw_scaleControl{min-width:0;flex:1;justify-content:flex-end}',
  '.dshw_chipToggle{display:inline-flex;align-items:center;gap:6px;height:24px;padding:0 9px;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));border-radius:999px;background:transparent;font-size:11.5px;color:var(--dsw-alias-label-secondary,inherit);cursor:pointer;white-space:nowrap;transition:color .12s,border-color .12s,background-color .12s}',
  '.dshw_chipToggle:hover{border-color:var(--dsw-alias-brand-primary,#4aa3ff);background:var(--dsw-alias-interactive-bg-hover,rgba(127,127,127,.08))}',
  '.dshw_chipToggle input{margin:0;accent-color:var(--dsw-alias-brand-primary,#4aa3ff)}',
  '.dshw_acctScroll{border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));border-radius:8px;overflow-y:auto;max-height:58px;scrollbar-width:thin;scrollbar-color:var(--dsw-alias-border-l3,rgba(127,127,127,.35)) transparent;margin:2px 0}',
  '.dshw_acctScroll::-webkit-scrollbar{width:6px}',
  '.dshw_acctScroll::-webkit-scrollbar-thumb{background:var(--dsw-alias-border-l3,rgba(127,127,127,.35));border-radius:3px}',
  '.dshw_acctScroll .dshw_row{padding:2px 6px}',
  '.dshw_balanceCard.dshw_low{border-color:var(--dsw-alias-state-error-primary,#e5534b)}',
  '.dshw_balanceCard.dshw_low .dshw_balNum{color:var(--dsw-alias-state-error-primary,#e5534b)}',
  '.dshw_chipLow .dshw_chipMain>span:not(.dshw_homePrimary):not(.dshw_sep){color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_chipLow .dshw_thirdText .dshw_homePrimaryValue{color:inherit}',
  '.dshw_chipLow .dshw_balanceText .dshw_homePrimaryLabel{color:var(--dsw-alias-label-primary,inherit)!important}',
  '.dshw_chipLow .dshw_balanceText .dshw_homePrimaryValue{color:var(--dsw-alias-state-error-primary,#e5534b)!important}',
  '.dshw_chipLow.dshw_chipVertical .dshw_chipMain>.dshw_metric:not(:first-child) .dshw_metricLabel,.dshw_chipLow.dshw_chipVertical .dshw_chipMain>.dshw_metric:not(:first-child) .dshw_metricValue{color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_chipLow.dshw_chipVertical .dshw_chipMain>.dshw_metric:first-child .dshw_metricValue{color:var(--dsw-alias-state-error-primary,#e5534b)}',
  '.dshw_chipLow.dshw_chipVertical .dshw_chipMain>.dshw_metric:first-child .dshw_metricLabel{color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_chipLow.dshw_noBlink{animation:none}',
  '.dshw_acctMore{display:flex;justify-content:flex-end;font-size:10.5px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085));margin-top:3px}',
  ''.trim() || '.dshw_acctRow{display:flex;align-items:center;gap:5px;padding:2px 6px;min-height:26px}',
  '.dshw_acctRow+.dshw_acctRow{border-top:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.12))}',
  '.dshw_acctRow.current{background:var(--dsw-alias-brand-soft,rgba(74,163,255,.10))}',
  '.dshw_acctAvatar{flex:none;width:18px;height:18px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;font-size:10px;font-weight:650;user-select:none}',
  '.dshw_acctInfo{flex:1;min-width:0;display:flex;align-items:center;gap:6px}',
  '.dshw_acctName{font-size:11.5px;font-weight:550;color:var(--dsw-alias-label-primary,inherit);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;flex:0 1 auto}',
  '.dshw_acctBadge{flex:none;font-size:9.5px;color:var(--dsw-alias-brand-primary,#4aa3ff);border:1px solid var(--dsw-alias-brand-primary,#4aa3ff);border-radius:4px;padding:0 4px;line-height:14px;opacity:.85}',
  '.dshw_acctKey{font-family:ui-monospace,Consolas,monospace;font-size:10px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085));white-space:nowrap;overflow:hidden;text-overflow:ellipsis;flex:1 1 auto}',
  '.dshw_acctNow{flex:none;padding:1px 7px;border-radius:999px;background:var(--dsw-alias-brand-soft,rgba(74,163,255,.14));color:var(--dsw-alias-brand-primary,#4aa3ff);font-size:10.5px;font-weight:550;line-height:16px}',
  '.dshw_settingsSection .dshw_setCard{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--dsw-alias-border-l1,rgba(127,127,127,.12))}',
  '.dshw_settingsSection .dshw_setCell{background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,transparent));border-top:none!important;padding:8px 10px}',
  '.dshw_settingsSection .dshw_setCell:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(127,127,127,.08))}',
  '.dshw_settingsSection .dshw_setCell.wide{grid-column:1/-1}',
  '.dshw_settingsSection{--dshw-card-radius:11px;max-width:900px;gap:12px!important}',
  '.dshw_settingsHeader{display:flex;align-items:flex-end;justify-content:space-between;gap:12px}',
  '.dshw_settingsHeading{font-size:16px;font-weight:650;letter-spacing:-.01em;color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_settingsLead{margin-top:2px;font-size:11.5px;color:var(--dsw-alias-label-tertiary,var(--dsw-alias-label-secondary,#667085))}',
  '.dshw_versionBadge{flex:none;padding:2px 7px;border-radius:999px;background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,rgba(127,127,127,.1)));color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085));font-size:10px}',
  '.dshw_settingsHero{border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.2));border-radius:var(--dshw-card-radius);background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,rgba(127,127,127,.05)));color:var(--dsw-alias-label-primary,inherit);padding:13px 15px}',
  '.dshw_settingsHero.dshw_low{border-color:var(--dsw-alias-state-error-primary,#e5534b)}',
  '.dshw_settingsHeroTop{display:flex;align-items:center;gap:8px}',
  '.dshw_settingsHeroLabel{font-size:11.5px;color:var(--dsw-alias-label-tertiary,var(--dsw-alias-label-secondary,#667085))}',
  '.dshw_accountPill{display:inline-flex;align-items:center;max-width:180px;padding:2px 7px;border-radius:999px;background:var(--dsw-alias-brand-soft,rgba(74,163,255,.10));color:var(--dsw-alias-label-secondary,inherit);font-size:10.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  '.dshw_settingsHeroMain{display:flex;align-items:flex-end;gap:18px;margin-top:7px}',
  '.dshw_settingsBalance{font-size:28px;font-weight:700;line-height:1;font-variant-numeric:tabular-nums;letter-spacing:-.025em}',
  '.dshw_settingsHero.dshw_low .dshw_settingsBalance{color:var(--dsw-alias-state-error-primary,#e5534b)}',
  '.dshw_settingsSpend{display:flex;flex-direction:column;gap:2px;padding-bottom:1px}',
  '.dshw_settingsSpend strong{font-size:14px;font-variant-numeric:tabular-nums}',
  '.dshw_settingsHeroMeta{display:flex;align-items:center;gap:7px;margin-top:9px;color:var(--dsw-alias-label-tertiary,var(--dsw-alias-label-secondary,#667085));font-size:11px;white-space:nowrap}',
  '.dshw_settingsGrid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:10px}',
  '.dshw_settingsSection .dshw_setCard{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:0;border:0;background:transparent;overflow:visible}',
  '.dshw_settingsSection .dshw_setCard>.dshw_setCell{min-width:0;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.2))!important;border-radius:var(--dshw-card-radius);background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,rgba(127,127,127,.05)));padding:11px 12px;color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_settingsSection .dshw_setCard>.dshw_setCell:hover{background:var(--dsw-alias-interactive-bg-hover,var(--dsw-alias-bg-layer-1,rgba(127,127,127,.09)))}',
  '.dshw_settingsSection .dshw_setCard>.dshw_setCell.wide{grid-column:1/-1}',
  '.dshw_reminderCard{display:block!important;padding:0!important;overflow:hidden}',
  '.dshw_settingsGroup{min-width:0;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.2));border-radius:var(--dshw-card-radius);background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,rgba(127,127,127,.05)));overflow:hidden;color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_settingsGroupHeader{padding:10px 12px;border-bottom:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.12))}',
  '.dshw_settingsGroupTitle{font-size:12px;font-weight:650;color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_settingsGroupHint{margin-top:2px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085));font-size:10.5px}',
  '.dshw_settingsField{display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:42px;padding:8px 12px}',
  '.dshw_settingsField+.dshw_settingsField{border-top:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.1))}',
  '.dshw_settingsFieldLabel{display:flex;min-width:0;flex-direction:column;gap:2px}',
  '.dshw_settingsFieldLabel>strong{font-size:11.5px;font-weight:550;color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_settingsFieldLabel>span{font-size:10px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '.dshw_settingsInline{display:flex;align-items:center;justify-content:flex-end;gap:6px;min-width:0}',
  '.dshw_settingsInline .dshw_input{height:26px;box-sizing:border-box}',
  '.dshw_settingsInline .dshw_select{height:26px}',
  '.dshw_settingChoices{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:9px 12px}',
  '.dshw_settingChoice{display:flex;align-items:center;justify-content:space-between;gap:8px;min-width:0;padding:7px 9px;border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.15));border-radius:8px;background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,rgba(127,127,127,.04)));color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_settingChoice:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(127,127,127,.08))}',
  '.dshw_settingChoiceCopy{min-width:0;display:flex;flex-direction:column;gap:1px}',
  '.dshw_settingChoiceCopy strong{font-size:11px;font-weight:550;white-space:nowrap;color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_settingChoiceCopy span{font-size:9.5px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085));white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  '.dshw_priceForm{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;align-items:end;padding:10px 12px}',
  '.dshw_priceField{display:grid;gap:4px;min-width:0}',
  '.dshw_priceField>span{font-size:9.5px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '.dshw_priceField .dshw_input,.dshw_priceField .dshw_select{box-sizing:border-box;width:100%;height:28px}',
  '.dshw_priceWindowEditor{display:grid;gap:7px;margin:0 12px 10px;padding:9px;border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.15));border-radius:9px;background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,rgba(127,127,127,.035)))}',
  '.dshw_priceWindowToolbar{display:flex;align-items:end;justify-content:space-between;gap:8px;flex-wrap:wrap}.dshw_priceWindowToolbar .dshw_priceField{min-width:180px;flex:1}',
  '.dshw_priceWindowList{display:grid;gap:7px}.dshw_priceWindow{display:grid;gap:7px;padding:8px;border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.14));border-radius:8px;background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,rgba(127,127,127,.03)))}',
  '.dshw_priceWindowHead{display:flex;align-items:end;gap:7px}.dshw_priceWindowHead .dshw_priceField{flex:1}',
  '.dshw_priceDays{display:flex;align-items:center;gap:4px;flex-wrap:wrap}.dshw_priceDays>span{margin-right:2px;font-size:9.5px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '.dshw_priceDay{width:25px;height:24px;padding:0;border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.18));border-radius:5px;background:transparent;color:var(--dsw-alias-label-secondary,inherit);font-size:10px;cursor:pointer}.dshw_priceDay[aria-pressed="true"]{border-color:var(--dsw-alias-brand-primary,#4aa3ff);background:var(--dsw-alias-brand-soft,rgba(74,163,255,.12));color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_priceWindowRates{display:grid;grid-template-columns:repeat(6,minmax(72px,1fr));gap:7px}',
  '.dshw_priceRules{display:grid;gap:6px;padding:0 12px 11px}',
  '.dshw_priceRule{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:7px 9px;border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.15));border-radius:8px;background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,rgba(127,127,127,.04)))}',
  '.dshw_priceRule strong,.dshw_priceRule span{display:block;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.dshw_priceRule strong{font-size:11px}.dshw_priceRule span{font-size:9.5px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '@media(max-width:760px){.dshw_priceForm{grid-template-columns:repeat(2,minmax(0,1fr))}.dshw_priceForm>.dshw_btn{min-height:28px}.dshw_priceWindowRates{grid-template-columns:repeat(2,minmax(0,1fr))}}',
  '.dshw_switch{position:relative;flex:none;width:34px;height:20px;display:inline-flex;cursor:pointer}',
  '.dshw_switch>input{position:absolute;inset:0;opacity:0;margin:0;cursor:pointer}',
  '.dshw_track{position:absolute;inset:0;border-radius:999px;background:var(--dsw-alias-border-l3,rgba(127,127,127,.3));transition:background-color .15s}',
  '.dshw_knob{position:absolute;left:2px;top:2px;width:16px;height:16px;border-radius:50%;background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,transparent));box-shadow:0 1px 3px rgba(0,0,0,.24);transition:transform .15s}',
  '.dshw_switch>input:checked+.dshw_track{background:var(--dsw-alias-brand-primary,#4aa3ff)}',
  '.dshw_switch>input:checked~.dshw_knob{transform:translateX(14px)}',
  '.dshw_switch>input:focus-visible+.dshw_track{outline:2px solid var(--dsw-alias-brand-primary,#4aa3ff);outline-offset:2px}',
  '.dshw_switch>input:disabled+.dshw_track{opacity:.38}.dshw_switch>input:disabled~.dshw_knob{opacity:.7}',
  '.dshw_accountHeader{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:2px}',
  '.dshw_accountCount{font-size:10.5px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '.dshw_settingsSection .dshw_acctScroll{max-height:150px;margin:0;border-radius:var(--dshw-card-radius)}',
  '.dshw_settingsSection .dshw_acctRow{min-height:38px;padding:6px 9px;gap:8px}',
  '.dshw_settingsSection .dshw_acctAvatar{width:24px;height:24px;font-size:11px}',
  '.dshw_settingsSection .dshw_acctInfo{align-items:flex-start;flex-direction:column;gap:1px}',
  '.dshw_settingsSection .dshw_acctName{font-size:11.5px}',
  '.dshw_settingsSection .dshw_acctKey{font-size:9.5px}',
  '.dshw_accountAdd{display:grid;grid-template-columns:120px minmax(150px,1fr) auto;gap:6px;padding:9px;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.2));border-radius:var(--dshw-card-radius);background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,rgba(127,127,127,.04)))}',
  '.dshw_accountAdd .dshw_input{box-sizing:border-box;width:100%;height:28px}',
  '.dshw_planCard{border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.2));border-radius:var(--dshw-card-radius,10px);background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,transparent));overflow:hidden}',
  '.dshw_planHeader{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:9px 10px;border:0;background:transparent;color:var(--dsw-alias-label-primary,inherit);width:100%;box-sizing:border-box;text-align:left}',
  '.dshw_planHeaderButton{cursor:pointer}.dshw_planHeaderButton:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(127,127,127,.08))}',
  '.dshw_planHeaderCopy{display:flex;min-width:0;flex-direction:column;gap:2px}.dshw_planTitle{font-weight:650;font-size:12px}.dshw_planHint{font-size:10.5px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '.dshw_planSources{display:flex;flex-direction:column;gap:7px;padding:0 9px 9px}.dshw_planSource{border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.16));border-radius:9px;padding:8px;background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,rgba(127,127,127,.04)))}',
  '.dshw_planSourceHead{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.dshw_planSourceName{font-size:11.5px;font-weight:650}.dshw_planSourceMeta{font-size:9.5px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085));overflow-wrap:anywhere}',
  '.dshw_planBadge{flex:none;padding:1px 6px;border-radius:999px;background:var(--dsw-alias-bg-layer-3,rgba(127,127,127,.1));color:var(--dsw-alias-label-secondary,inherit);font-size:9.5px}.dshw_planBadge.ok{background:var(--dsw-alias-state-success-soft,rgba(44,170,110,.13));color:var(--dsw-alias-state-success-primary,#2ca96f)}.dshw_planBadge.warn{background:var(--dsw-alias-state-warning-soft,rgba(218,155,45,.14));color:var(--dsw-alias-state-warning-primary,#b7791f)}',
  '.dshw_planLimits{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:7px}.dshw_planLimit{min-width:0;padding:7px;border-radius:8px;background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,rgba(127,127,127,.04)))}',
  '.dshw_planLimitTop,.dshw_planLimitMeta{display:flex;align-items:center;justify-content:space-between;gap:6px}.dshw_planLimitTop{font-size:10.5px;font-weight:600}.dshw_planLimitMeta{margin-top:4px;font-size:9.5px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '.dshw_planBar{height:5px;margin-top:6px;border-radius:999px;overflow:hidden;background:var(--dsw-alias-bg-layer-3,rgba(127,127,127,.14))}.dshw_planBarFill{height:100%;border-radius:inherit;background:var(--dsw-alias-state-success-primary,var(--dsw-alias-brand-primary,#4aa3ff));transition:width .18s ease}.dshw_planBarFill.warn{background:var(--dsw-alias-state-warning-primary,#b7791f)}.dshw_planBarFill.critical{background:var(--dsw-alias-state-error-primary,#e5534b)}',
  '.dshw_settingsFooter{display:flex;align-items:center;justify-content:space-between;gap:10px;padding-top:2px}',
  '.dshw_settingsFooterActions{display:flex;align-items:center;gap:7px}',
  '.dshw_settingsFooter .dshw_btn{height:30px;padding:0 14px}',
  '.dshw_footRing{width:100%;box-sizing:border-box;display:flex;align-items:center;gap:8px;margin:2px 0 8px;padding:7px 9px;border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.18));border-radius:11px;background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,rgba(127,127,127,.04)));color:var(--dsw-alias-label-primary,inherit);font-size:12.5px;cursor:grab;user-select:none;touch-action:none;transition:border-color .15s ease,background-color .15s ease}',
  'body[data-dsh-maid-atelier]:not([data-ds-dark-theme]) .dshw_footRing{--dsw-alias-label-primary:#f8f3e8;--dsw-alias-label-secondary:#d7def0;--dsw-alias-label-tertiary:#b5c1dd;--dsw-alias-border-l1:rgba(225,191,124,.62);--dsw-alias-border-l3:rgba(181,196,229,.34);--dsw-alias-interactive-bg-hover:rgba(41,61,111,.98);color:#f8f3e8;background:linear-gradient(145deg,rgba(34,55,106,.95),rgba(10,25,62,.97));border-color:rgba(225,191,124,.62);box-shadow:inset 0 0 0 2px rgba(5,15,45,.44),0 4px 11px rgba(1,7,24,.22)}',
  'body[data-dsh-maid-atelier][data-ds-dark-theme] .dshw_footRing{--dsw-alias-label-primary:#f8f3e8;--dsw-alias-label-secondary:#d7def0;--dsw-alias-label-tertiary:#b5c1dd;--dsw-alias-border-l1:rgba(211,180,119,.52);--dsw-alias-border-l3:rgba(181,196,229,.34);--dsw-alias-interactive-bg-hover:rgba(41,61,111,.96);color:#f8f3e8;background:rgba(18,32,70,.92);border-color:rgba(211,180,119,.52);box-shadow:inset 0 1px rgba(255,255,255,.07),0 4px 12px rgba(0,0,0,.24)}',
  '.dshw_footRing[data-dshw-peak-background="transparent"]:not(.dshw_footRingFloating){background:transparent;box-shadow:none}',
  '.dshw_footRing[data-dshw-peak-background="transparent"]:not(.dshw_footRingFloating):hover{background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,rgba(127,127,127,.04)));box-shadow:none}',
  'body[data-dsh-maid-atelier] .dshw_footRing[data-dshw-peak-background="transparent"]:not(.dshw_footRingFloating){background:transparent;box-shadow:none}',
  'body[data-dsh-maid-atelier]:not([data-ds-dark-theme]) .dshw_footRing[data-dshw-peak-background="transparent"]:not(.dshw_footRingFloating):hover{background:linear-gradient(145deg,rgba(34,55,106,.95),rgba(10,25,62,.97));box-shadow:inset 0 0 0 2px rgba(5,15,45,.44),0 4px 11px rgba(1,7,24,.22)}',
  'body[data-dsh-maid-atelier][data-ds-dark-theme] .dshw_footRing[data-dshw-peak-background="transparent"]:not(.dshw_footRingFloating):hover{background:rgba(18,32,70,.92);box-shadow:inset 0 1px rgba(255,255,255,.07),0 4px 12px rgba(0,0,0,.24)}',
  '.dshw_footRing:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(127,127,127,.1));border-color:var(--dsw-alias-border-l2,rgba(127,127,127,.28))}',
  '.dshw_footRing.dshw_low{border-color:var(--dsw-alias-state-error-primary,#e5534b)}',
  '.dshw_footRingRail{width:42px;height:42px;min-height:42px;margin:3px 0 6px;padding:0;justify-content:center;border-radius:50%;background:transparent;border:none;cursor:pointer}',
  '.dshw_footRingRail:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(127,127,127,.1))}',
  '.dshw_footRingVertical{flex-direction:column;align-items:center;text-align:center;width:fit-content;min-width:132px;max-width:152px;margin:2px auto 8px;padding:8px 8px;gap:4px;overflow:visible}',
  '.dshw_footRingVertical .dshw_footRingLabel{align-items:center;text-align:center;width:100%;gap:3px;overflow:visible}',
  '.dshw_footRingVertical .dshw_footRingHeader{justify-content:center}',
  '.dshw_footRingVertical .dshw_footRingTitle{font-size:13px}',
  '.dshw_footRingVertical .dshw_footRingMoney{justify-content:center;font-size:11px;overflow:visible;white-space:nowrap;width:100%}',
  '.dshw_footRingVertical .dshw_footRingCountdown{font-size:10.5px;overflow:visible;white-space:nowrap}',
  '.dshw_footRingVertical .dshw_footRingBottom{justify-content:center}',
  '.dshw_footRingNoRecharge{padding-right:10px}',
  '.dshw_footRingFloating{position:fixed;z-index:90;width:auto;min-width:180px;max-width:260px;margin:0!important;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,transparent)));box-shadow:0 8px 24px rgba(0,0,0,.35);cursor:grab;touch-action:none}',
  '.dshw_footRingFloating.dshw_footRingVertical{min-width:132px;max-width:152px;width:140px;padding:9px 8px;gap:4px}',
  '.dshw_footRingFloating.dshw_footRingVertical .dshw_footRingResetBtn{position:absolute;top:4px;right:4px;font-size:9.5px;padding:1px 5px;line-height:13px}',
  '.dshw_footRingFloating.dshw_footRingDragging{cursor:grabbing;box-shadow:0 10px 30px rgba(0,0,0,.45)}',
  '.dshw_footRingResetBtn{position:absolute;top:4px;right:6px;font-size:10px;padding:1px 6px;border-radius:4px;border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.2));background:var(--dsw-alias-bg-layer-2,transparent);color:var(--dsw-alias-label-tertiary,var(--dsw-alias-label-secondary,#667085));cursor:pointer;line-height:14px}',
  '.dshw_footRingResetBtn:hover{color:var(--dsw-alias-label-primary,inherit);border-color:var(--dsw-alias-brand-primary,#4aa3ff)}',
  '.dshw_footRingLabel{flex:1 1 auto;min-width:0;display:flex;flex-direction:column;justify-content:center;gap:3px;overflow:hidden}',
  '.dshw_footRingHeader{display:flex;align-items:center;gap:6px;white-space:nowrap}',
  '.dshw_footRingTitle{font-size:13.5px;font-weight:700;line-height:1.2;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.dshw_footRingBadge{font-size:10px;font-weight:600;padding:1px 5px;line-height:15px;border-radius:3px;flex:none}',
  '.dshw_footRingBadgePeak{background:var(--dsw-alias-state-error-soft,rgba(229,83,75,.12));color:var(--dsw-alias-state-error-primary,#e5534b)}',
  '.dshw_footRingBadgeOff{background:var(--dsw-alias-state-success-soft,rgba(26,127,55,.12));color:var(--dsw-alias-state-success-primary,#1a7f37)}',
  '.dshw_footRingMoney{font-size:12.5px;font-variant-numeric:tabular-nums;line-height:1.25;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  '.dshw_footRingMoneyGroup{display:inline-flex;white-space:nowrap}',
  '.dshw_footRingMoney.dshw_low .dshw_footBalNum{color:var(--dsw-alias-state-error-primary,#e5534b);font-weight:700}',
  '.dshw_footRingBottom{display:flex;align-items:center;justify-content:space-between;gap:6px;width:100%;min-height:18px}',
  '.dshw_footRingCountdown{font-size:11px;color:var(--dsw-alias-label-secondary,rgba(127,127,127,.85));line-height:1.2;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;flex:1 1 auto;min-width:0}',
  '.dshw_footRingBtnRechargeInline{border:1px solid var(--dsw-alias-brand-primary,#4aa3ff);background:var(--dsw-alias-brand-soft,rgba(74,163,255,.10));color:var(--dsw-alias-brand-primary,#4aa3ff);border-radius:4px;height:18px;padding:0 6px;font-size:10.5px;font-weight:600;line-height:16px;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;transition:all .15s ease;user-select:none;flex:none}',
  '.dshw_footRingBtnRechargeInline:hover{background:var(--dsw-alias-brand-primary,#4aa3ff);color:var(--dsw-alias-label-primary-foreground,var(--dsw-alias-label-primary,inherit))}',
  '.dshw_footRingNarrow{align-items:flex-start;gap:6px;padding-left:7px;padding-right:7px}',
  '.dshw_footRingNarrow .dshw_footRingLabel{overflow:visible}',
  '.dshw_footRingNarrow .dshw_footRingMoney{display:flex;flex-wrap:wrap;column-gap:3px;row-gap:0;overflow:visible;text-overflow:clip;white-space:normal}',
  '.dshw_footRingNarrow .dshw_footRingMoney>.dshw_balDot{display:none}',
  '.dshw_footRingNarrow .dshw_footRingBottom{align-items:flex-start;flex-wrap:wrap;row-gap:3px}',
  '.dshw_footRingNarrow .dshw_footRingCountdown{flex-basis:100%;overflow:visible;text-overflow:clip;white-space:normal}',
  '.dshw_footRingNarrow .dshw_footRingBtnRechargeInline{margin-left:auto}',
  '.dshw_peakPanel{position:fixed;z-index:95;width:290px;box-sizing:border-box;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,transparent)));color:var(--dsw-alias-label-primary,inherit);border-radius:12px;box-shadow:0 10px 32px rgba(0,0,0,.38);display:flex;flex-direction:column;gap:8px;padding:12px 14px;font-size:12px;user-select:none;touch-action:none}',
  '.dshw_peakPanelHeader{display:flex;align-items:center;justify-content:space-between;font-weight:650;font-size:12.5px;color:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_peakPanelClose{border:none;background:transparent;color:inherit;font-size:16px;line-height:1;cursor:pointer;padding:2px 6px;border-radius:4px}',
  '.dshw_peakPanelClose:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(127,127,127,.12))}',
  '.dshw_peakStatusCard{padding:8px 10px;border-radius:8px;border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.15));background:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,rgba(127,127,127,.05)));display:flex;flex-direction:column;gap:3px}',
  '.dshw_peakRow{display:flex;align-items:center;justify-content:space-between;gap:8px;min-height:26px}',
  '.dshw_ringPeak{stroke:var(--dsw-alias-state-error-primary,#e5534b)}',
  '.dshw_ringOff{stroke:var(--dsw-alias-state-success-primary,#1a7f37)}',
  '.dshw_ringNeutral{stroke:var(--dsw-alias-border-l3,rgba(127,127,127,.3))}',
  '.dshw_peakRing circle{transition:stroke-width .3s ease}',
  '.dshw_ringNow{stroke-width:6;filter:brightness(1.15)}',
  '.dshw_ringPointer{fill:var(--dsw-alias-label-primary,inherit)}',
  '.dshw_ringTick{fill:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085))}',
  '@media (max-width:760px){.dshw_settingsGrid,.dshw_settingsSection .dshw_setCard{grid-template-columns:1fr}.dshw_settingsSection .dshw_setCard>.dshw_setCell.wide{grid-column:1}.dshw_accountAdd{grid-template-columns:1fr}.dshw_planLimits{grid-template-columns:1fr}.dshw_settingsFooter{align-items:flex-start;flex-direction:column-reverse}.dshw_settingsFooterActions{width:100%}.dshw_settingsFooterActions .dshw_btn{flex:1}.dshw_settingsHeroMeta{white-space:normal;flex-wrap:wrap}}',      '@media (max-width:560px){.dshw_settingsHostDialog{flex-direction:column!important}.dshw_settingsHostDialog>nav{box-sizing:border-box!important;width:100%!important;min-width:0!important;height:auto!important;flex:none!important;padding:8px 10px 0!important}.dshw_settingsHostDialog>nav>div:first-child{display:none!important}.dshw_settingsHostDialog>nav>div:nth-child(2){box-sizing:border-box!important;width:100%!important;height:auto!important;flex-direction:row!important;gap:4px!important;overflow-x:auto!important;padding-bottom:6px!important}.dshw_settingsHostDialog>nav>div:nth-child(2)>button{width:auto!important;min-width:max-content!important;height:34px!important;flex:0 0 auto!important;padding:0 10px!important}.dshw_settingsHostDialog>div{width:100%!important;min-width:0!important;flex:1 1 auto!important}.dshw_settingsSection{box-sizing:border-box;width:100%!important;min-width:0!important}.dshw_historyActions .dshw_btn{flex:1 1 auto}}',
  '.dshw_actionRow{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:2px 0}',
  '.dshw_textDanger{display:inline-flex;align-items:center;gap:5px;height:22px;padding:0 4px;border:none;background:transparent;font:inherit;font-size:11px;color:var(--dsw-alias-label-secondary,var(--dsw-alias-label-tertiary,#667085));cursor:pointer;border-radius:4px;transition:color .12s,background-color .12s}',
  '.dshw_textDanger:hover{color:var(--dsw-alias-state-error-primary,#e5534b);background:var(--dsw-alias-state-error-soft,rgba(229,83,75,.12))}',
  '.dshw_overlay{position:fixed;inset:0;background:var(--dsw-alias-bg-mask-drop,rgba(0,0,0,.55));display:flex;align-items:center;justify-content:center;z-index:100}',
  '.dshw_overlayBox{background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,transparent)));border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));color:var(--dsw-alias-label-primary,inherit);border-radius:8px;padding:14px 18px;width:min(320px,calc(100vw - 32px));box-sizing:border-box;font-size:13px;line-height:1.7}',
  '.dshw_overlayRow{margin-top:10px;display:flex;gap:8px;justify-content:flex-end}',
  '.dshw_float{position:fixed;z-index:80;min-width:230px;max-width:280px;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,transparent)));color:var(--dsw-alias-label-primary,inherit);border-radius:12px;box-shadow:0 6px 20px rgba(0,0,0,.25);display:flex;flex-direction:column;gap:6px;padding:10px 12px;font-size:12px;user-select:none}',
  '.dshw_floatHeader{display:flex;align-items:center;justify-content:space-between;cursor:move;font-weight:600;opacity:.9;touch-action:none}',
  '.dshw_floatBtn{border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));background:transparent;color:inherit;border-radius:5px;width:22px;height:20px;font-size:12px;line-height:1;cursor:pointer;padding:0}',
  '.dshw_floatBtn:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(127,127,127,.1))}',
  '.dshw_dot{position:fixed;z-index:80;width:36px;height:36px;border-radius:50%;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,transparent)));color:var(--dsw-alias-label-primary,inherit);font-size:11px;display:flex;align-items:center;justify-content:center;cursor:pointer;box-shadow:0 2px 10px rgba(0,0,0,.25);user-select:none;touch-action:none}',
  '.dshw_dotLow{border-color:var(--dsw-alias-state-error-primary,#e5534b);color:var(--dsw-alias-state-error-primary,#e5534b)}',
  '.dshw_noticeStack{position:fixed;z-index:120;top:max(12px,env(safe-area-inset-top));right:max(12px,env(safe-area-inset-right));width:min(340px,calc(100vw - 24px));display:flex;flex-direction:column;gap:8px;pointer-events:none}',
  '.dshw_notice{box-sizing:border-box;width:100%;display:flex;align-items:flex-start;gap:8px;padding:10px 10px 10px 12px;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.25));border-radius:9px;background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,transparent)));color:var(--dsw-alias-label-primary,inherit);box-shadow:0 6px 20px rgba(0,0,0,.25);font-size:12px;line-height:1.45;pointer-events:auto;cursor:pointer}',
  '.dshw_noticeCopy{min-width:0;display:flex;flex:1;flex-direction:column;gap:2px}.dshw_noticeCopy span{white-space:pre-line;overflow-wrap:anywhere}',
  '.dshw_noticeClose{flex:none;width:24px;height:24px;border:0;border-radius:5px;background:transparent;color:inherit;font-size:18px;line-height:1;cursor:pointer}.dshw_noticeClose:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(127,127,127,.1))}',
  // Home-fit and compact modes are toggled by measured space (see the
  // home-space effect in WalletChip), not by container queries:
  // container-type:inline-size on a content-sized flex item detaches its
  // width from the chip, so flex layouts resolve it to min-width (44px)
  // even when the row has room.
  '.dshw_anchorHome.dshw_fit .dshw_chipMain>span:not(.dshw_homePrimary){display:none}',
  '.dshw_anchorHome.dshw_compact .dshw_chip{width:100%}.dshw_anchorHome.dshw_compact .dshw_chipMain{box-sizing:border-box;width:100%;min-width:0;overflow:hidden;justify-content:center;padding:0 3px}.dshw_anchorHome.dshw_compact .dshw_chipMain>span{display:none}.dshw_anchorHome.dshw_compact .dshw_chipMain>.dshw_homePrimary{display:inline;min-width:0;overflow:hidden;text-overflow:ellipsis}.dshw_anchorHome.dshw_compact .dshw_homePrimaryLabel{display:none}.dshw_anchorHome.dshw_compact .dshw_recharge{display:none}',
  '@media (max-width:420px){.dshw_chipDocked:not(.dshw_chipVertical){max-width:calc(100vw - 4px);font-size:10px}.dshw_chipDocked:not(.dshw_chipVertical) .dshw_chipMain{gap:3px;padding:0 4px}.dshw_chipDocked:not(.dshw_chipVertical) .dshw_recharge{padding:0 4px}}'
].join('')

if (typeof document !== 'undefined' && document.querySelector('style[data-plugin="deepseek-harness-wallet"]') === null) {
  var tag = document.createElement('style')
  tag.dataset.plugin = 'deepseek-harness-wallet'
  tag.textContent = css
  document.head.appendChild(tag)
}

